#!/bin/bash

# Set the name of the private key
private_key="school"

# Set the number of bits for the key
bits=4096

# Set the passphrase
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b "$bits" -C "Generated by script" -f "$private_key" -N "$passphrase"

# Check if the key pair generation was successful
if [ $? -eq 0 ]; then
    echo "RSA key pair successfully generated."
    echo "Private key: $private_key"
    echo "Public key: $private_key.pub"
else
    echo "Error generating RSA key pair."
fi
