"""Initial migration

Revision ID: dc57954821a6
Revises: 
Create Date: 2023-05-31 07:20:02.858337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc57954821a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('roll_number', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_course',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.drop_table('user')
    op.drop_table('department')
    op.drop_table('trig')
    op.drop_table('student')
    op.drop_table('test')
    op.drop_table('attendence')
    op.add_column('marks', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('marks', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('marks', sa.Column('marks', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'marks', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'marks', 'students', ['student_id'], ['id'])
    op.drop_column('marks', 'rollno')
    op.drop_column('marks', 'mid_1')
    op.drop_column('marks', 'final')
    op.drop_column('marks', 'mid_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('mid_2', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False))
    op.add_column('marks', sa.Column('final', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False))
    op.add_column('marks', sa.Column('mid_1', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False))
    op.add_column('marks', sa.Column('rollno', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False))
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_column('marks', 'marks')
    op.drop_column('marks', 'course_id')
    op.drop_column('marks', 'student_id')
    op.create_table('attendence',
    sa.Column('aid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rollno', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=False),
    sa.Column('attendance', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('aid'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=52), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rollno', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('sname', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('sem', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('branch', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('number', mysql.VARCHAR(collation='utf8mb4_general_ci', length=12), nullable=False),
    sa.Column('address', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('trig',
    sa.Column('tid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rollno', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('action', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('tid'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('department',
    sa.Column('cid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('cid'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('student_course')
    op.drop_table('attendance')
    op.drop_table('students')
    op.drop_table('courses')
    # ### end Alembic commands ###
